# Generated by Django 5.0.6 on 2024-05-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_userdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='userdetail',
        ),
    ]
