# Generated by Django 5.0.6 on 2024-05-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0003_rename_user_review_userdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetail',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='userdetail',
            new_name='user',
        ),
    ]
