# Generated by Django 5.0.6 on 2024-05-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
    ]
